### PR TITLE
add block-size config flag

### LINKED ISSUE #6: add config for block size
Different companies using different styles. As for me functions of blocks with 2-5 lines of code look good and clear enough.

It will be great to add a flag to configure the block size.

### PR DESCRIPTION
**Pull request by kulti**
Fixes #6

### CODE REVIEW

**Comment by TomBrouws** [comment]
This is exactly the change that we need to use this linter in our company. Can we get this merged?

**Comment by bconway** [comment]
This would be very helpful. @ssgreg any thoughts?

**Comment by tsologub** [comment]
@kulti seems some checks have failed. Could you please take a look? This PR is a lifesaver.

**Comment by kulti** [comment]
@tsologub, done.

@ssgreg, could you please review and accept this pr?

**Comment by tsologub** [comment]
@wreulicke could you please take a look on this?

**Comment by butuzov** [comment]
@ssgreg ping. Can this PR be merged? Or the project is abandoned?

**Comment by tsologub** [comment]
Great news. Btw. can we expect a new release soon?

**Pull request merged**
