### PR TITLE
chores: replace `travis-ci` with `github actions`

### PR DESCRIPTION
**Pull request by butuzov**
1) this PR replaces travis-ci with github actions after the recent event
see
 - https://blog.travis-ci.com/2021-09-13-bulletin
 - https://twitter.com/peter_szilagyi/status/1437646118700175360

2) adds golangci-linter to ci
3) adds build stage to ci
4) adds go versions: 1.14, 1.15, 1.16 and 1.17 to CI tests.

Repo owner will need to add `COVERALLS_TOKEN` to `Repository Secrets` in
the settings tab.

### CODE REVIEW

**Comment by butuzov** [comment]
Worth to mention travis-ci.org didn't run for this repo in the past year

https://travis-ci.org/github/ssgreg/nlreturn/builds

**Comment by butuzov** [comment]
@ssgreg this PR isn't required, but OK to have for future development (at least we can have working CI).

**Comment by butuzov** [comment]
@ssgreg sorry to be annoying, but can we have at least #8 released? I can pin to git commit, but its better to have sem ver in `go.mod` instead git commit. please...

**Comment by ssgreg** [comment]
> @ssgreg sorry to be annoying, but can we have at least #8 released? I can pin to git commit, but its better to have sem ver in `go.mod` instead git commit. please...

hi, done -> v2.2.1

**Comment by butuzov** [comment]
thank you! #7 feature will be available soon with `golangci-lint`. cheers!

**Comment by ssgreg** [comment]
> thank you! #7 feature will be available soon with `golangci-lint`. cheers!

thank you!
you can write me directly to me@ssgreg.com

**Pull request closed without merging**
